version: '2'
services:
    autoecolev01-app:
        image: autoecolev01
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://autoecolev01-mariadb:3306/autoecolev01
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    autoecolev01-mariadb:
        extends:
            file: mariadb.yml
            service: autoecolev01-mariadb
